### ISSUE TITLE
Question: What happens if the WWW-Authenticate header returns a Resource Identifier with a different hostname?

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/draft-ietf-oauth-resource-metadata#16]
* Is this acceptable?
* What features does this enable?
* What are the security considerations of doing so?

In some situations it is impossible or impractical for a resource server to host content at `.well-known`.

**Comment by selfissued** [comment]
Per the proposed validation logic in PR #20, this is OK when the URL of the resource server used by the client matches the `resource` value returned in the metadata.

**Comment by selfissued** [comment]
Addressed by this language in PR #20:
> If the protected resource metadata was retrieved from a URL returned by the protected resource via the WWW-Authenticate resource_metadata parameter, then the resource value returned MUST be identical to the URL that the client used to make the request to the resource server. If these values are not identical, the data contained in the response MUST NOT be used.
