### ISSUE TITLE
Add flow diagrams

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/draft-ietf-oauth-resource-metadata#31]

**Comment by aaronpk** [comment]
![RS Metadata](https://github.com/oauth-wg/draft-ietf-oauth-resource-metadata/assets/113001/c267531b-1823-4efc-b16e-68e5ea4aa757)

Here's the SVG version. I need to make the ascii version of this next.

**Comment by selfissued** [comment]
Cc @PieterKas
