### ISSUE TITLE
Usage of /.well-known/ as specified is not licit

### ISSUE THREAD

**Issue by randomstuff** [oauth-wg/draft-ietf-oauth-resource-metadata#44]
The current draft states:

> The consumer of the metadata would make the following request when the resource identifier is https://resource.example.com/resource1 […]
>
>     GET /resource1/.well-known/oauth-protected-resource HTTP/1.1
>     Host: resource.example.com
> 
> Using path components enables supporting multiple resources per host. This is required in some multi-tenant hosting configurations. This use of .well-known is for supporting multiple resources per host; unlike its use in [[RFC5785](https://www.ietf.org/archive/id/draft-ietf-oauth-resource-metadata-01.html#RFC5785)], it does not provide general information about the host.

AFAIU, this approach does not respect the idea of RFC5785 which is to have a dedicated path **prefix**:

> To address this, this memo defines a **path prefix** in HTTP(S) URIs for
> these "well-known locations", "/.well-known/".

Moreover, this is not consistent with [server medata](https://www.rfc-editor.org/rfc/rfc8414#section-3.1) spec (which is completely similar):

> The client would make the following request when the
> issuer identifier is "https://example.com/issuer1" and the well-known
> URI suffix is "oauth-authorization-server" to obtain the metadata,
> since the issuer identifier contains a path component:
> 
>     GET /.well-known/oauth-authorization-server/issuer1 HTTP/1.1
>     Host: example.com

Therefore, I believe, the correct behavior would be to use `/.well-known/oauth-protected-resource/resource1`.

This does not preclude a multi-tenant application from serving the same information at `/resource1/.well-known/oauth-protected-resource` as well in order to facilitate exposing `https://service/resource1` as `https://resource1/`.

This does not preclude either redirecting `/app1/.well-known/oauth-protected-resource` to `/.well-known/oauth-protected-resource/app1` when serving multiple independant applications under the same origin.

**Comment by selfissued** [comment]
This behavior was corrected in https://datatracker.ietf.org/doc/draft-ietf-oauth-resource-metadata/02/.
