### ISSUE TITLE
Declaring support for DPoP and Certificate-Bound Access Tokens

### ISSUE THREAD

**Issue by randomstuff** [oauth-wg/draft-ietf-oauth-resource-metadata#48]
It would be interesting for the resource server to declare support for:

* [DPoP](https://datatracker.ietf.org/doc/html/rfc9449)
* [Certificate-Bound Access Token](https://www.rfc-editor.org/rfc/rfc8705)

The authorization server could use this information to detect that it can issue this type of access tokens for the target Resource Server.

**Comment by selfissued** [comment]
I will create a PR for people to review.  @bc-pi asks the question whether these should be booleans indicating support or whether they are required.  @aaronpk indicates that he doesn't believe that any current metadata parameters indicate REQUIRED.

I will also try to align the parameters with our existing metadata parameters for these topics.

**Comment by randomstuff** [comment]
I guess it would make sense to use properties which are similar to the existing AS metadata:

> **dpop_signing_alg_values_supported:**
> A JSON array containing a list of the JWS alg values
> (from the [[IANA.JOSE.ALGS](https://www.iana.org/assignments/jose/)] registry) supported
> by the authorization server for DPoP proof JWTs.
> 
> **tls_client_certificate_bound_access_tokens**
> OPTIONAL. Boolean value indicating server support for mutual-TLS client certificate-bound access tokens.
> If omitted, the default value is false.

Note: the last one does not really respect the tradition format of `xxxx_supported`.
