### ISSUE TITLE
Add motivating example for resource metadata to the spec

### ISSUE THREAD

**Issue by selfissued** [oauth-wg/draft-ietf-oauth-resource-metadata#50]
Per my reply to Bo Wu's OpsDir review:

> It seems that text in Introduction means that the resource server is prior knowledge of the client if I understand correctly. Am I correct?

> Mike> Actually, the client may learn about the resource server at runtime as a result of user interface actions by the person using the client.  The client might be, for instance, an e-mail reader and the resource might be an e-mail server.  The client can be pointed at any of thousands of e-mail servers worldwide, which would be the resources.

> Mike> Aaron Parecki did a good job explaining that motivating use case several IETFs ago.  I'll try to dig that up and we'll consider describing it in the draft.

@aaronpk, can you add your motivating example to the introduction?  Thanks!

**Comment by aaronpk** [comment]
I didn't mean to merge that PR without your review, so let me know if it looks good before I close this issue!

**Comment by selfissued** [comment]
Looks good!  The only change I made was to make the WebFinger reference informative.  Please close.

**Comment by aaronpk** [comment]
Good catch, not sure why that wasn't informative before.

**Comment by selfissued** [comment]
It was previously incorrectly normative.  I just happened to notice when reviewing your addition.  Thanks again!
